export const GET_DATE_RANGE_REQUEST = 'GET_DATE_RANGE_REQUEST';
export const GET_DATE_RANGE_SUCCESS = 'GET_DATE_RANGE_SUCCESS';
export const GET_DATE_RANGE_ERROR = 'GET_DATE_RANGE_ERROR';

export const GET_CHART1_DATA_REQUEST = 'GET_CHART1_DATA_REQUEST';
export const GET_CHART1_DATA_SUCCESS = 'GET_CHART1_DATA_SUCCESS';
export const GET_CHART1_DATA_ERROR = 'GET_CHART1_DATA_ERROR';

export const GET_CHART2_DATA_REQUEST = 'GET_CHART2_DATA_REQUEST';
export const GET_CHART2_DATA_SUCCESS = 'GET_CHART2_DATA_SUCCESS';
export const GET_CHART2_DATA_ERROR = 'GET_CHART2_DATA_ERROR';
